spring.application.name=config-server


server.port=8888


spring.cloud.config.server.git.uri=https://github.com/Varunkumar23/SmartSure_Configuration.git
spring.cloud.config.server.git.clone-on-start=true

spring.cloud.config.server.git.username=Varunkumar23
spring.cloud.config.server.git.password=${GIT_TOKEN}
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.endpoints.web.exposure.include=*

